### ISSUE TITLE
Additional species x aSMR statistics and output

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/aSMR-x-rSMR#2]
More work with the section for determining indicator status from the data - starting at line 286 or so
Currently generating 2 tables showing species by aSMR class for count (Spp_aSMR) or by  sum of covers (Spp_aSMRcov).
I want some more species statistics to play with building indicator values 
1. Convert the matrix values into a % of row totals
2. Remove matrix values of < 10% of occurrences
3. Add driest_aSMR, wettest_aSMR and modal_aSMR values to each species
From the raw spp_aSMRcov data:
Add output graphics of  bar plot and gaussian response curve of  species  over all aSMR classes. User selected individual species, or all species in a plot.

**Comment by kdaust** [comment]
I think this should address most of the first set of tasks - I wasn't sure about removing values less than 10%...

![image](https://user-images.githubusercontent.com/34073038/45936273-7d551780-bf69-11e8-97b1-7716bb59f798.png)

**Comment by kdaust** [comment]
Fixed stats output (I think), added ability to plot multiple curves. 
![image](https://user-images.githubusercontent.com/34073038/46124905-72a1b900-c1db-11e8-8bd2-73d2ac69514b.png)

**Comment by whmacken** [comment]
Great. I post a version of the Shiny script for the BEC summaries as you know. I’ll add a few tasks to the GItHub around that.

Sent from my iPhone

On Sep 26, 2018, at 22:28, Kiri Daust <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed stats output (I think), added ability to plot multiple curves.
[image]<https://user-images.githubusercontent.com/34073038/46124905-72a1b900-c1db-11e8-8bd2-73d2ac69514b.png>
